[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

;=============== Extension 1000 ===============

[1000]
type=endpoint
context=from-internal
disallow=all
allow=ulaw
allow=alaw
auth=1000
aors=1000
direct_media=no
force_rport=yes
rewrite_contact=yes
callerid=Alice <1000>

[1000]
type=auth
auth_type=userpass
username=1000
password=Str0ngPass1000

[1000]
type=aor
max_contacts=2
remove_existing=yes
qualify_frequency=30

;=============== Extension 1001 ===============

[1001]
type=endpoint
context=from-internal
disallow=all
allow=ulaw
allow=alaw
auth=1001
aors=1001
direct_media=no
force_rport=yes
rewrite_contact=yes
callerid=Bob <1001>

[1001]
type=auth
auth_type=userpass
username=1001
password=Str0ngPass1001

[1001]
type=aor
max_contacts=2
remove_existing=yes
qualify_frequency=30