[res_pjsip]
endpoint=realtime,ps_endpoints

[res_pjsip_endpoint_identifier_ip]
identify=realtime,ps_endpoint_id_ips

[res_pjsip_authenticator_digest]
auth=realtime,ps_auths

[res_pjsip_registrar]
aor=realtime,ps_aors
contact=realtime,ps_contacts