[general]
format=wav49|gsm|wav
attach=no
maxmsg=100
maxsecs=300
minsecs=2
maxsilence=10
silencethreshold=128
maxlogins=3
skipms=3000
moveheard=yes
sendvoicemail=no

[default]
1000 => 1234,Alice,,,attach=no
1001 => 1234,Bob,,,attach=no